apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-backend
  template:
    metadata:
      labels:
        app: java-backend
    spec:
      containers:
      - name: java-backend
        image: 866934333672.dkr.ecr.us-east-2.amazonaws.com/java-mongo:latest
        ports:
        - containerPort: 8080
       
