apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 5Gi  # The size of the persistent volume
  accessModes:
    - ReadWriteOnce  # The volume can be mounted as read-write by a single node
  persistentVolumeReclaimPolicy: Retain  # What to do with the volume after it's released
  storageClassName: manual
  hostPath:
    path: /mnt/data  # This path on the host will be used for storage (example for bare-metal or minikube)
